# fly.toml app configuration file generated for html-to-image-api on 2025-01-06T00:43:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "html-to-image-api"
primary_region = "waw"

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
